---
- name: Ensure the root user account cannot log into devices
  hosts: all
  tasks:
    - name: Install ClamAV through package manager
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
      become: true
      notify: Restart SSH server service
  handlers:
    - name: Restart SSH server service
      ansible.builtin.service:
        name: sshd
        state: restarted
      become: true
